//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerRunner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerRunner.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Running Power Track.
        /// </summary>
        public static string Label_CreatePowerTrack {
            get {
                return ResourceManager.GetString("Label_CreatePowerTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniels Points.
        /// </summary>
        public static string Label_DanielsPoints {
            get {
                return ResourceManager.GetString("Label_DanielsPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Power.
        /// </summary>
        public static string Label_NormPower {
            get {
                return ResourceManager.GetString("Label_NormPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIMP.
        /// </summary>
        public static string Label_TRIMP {
            get {
                return ResourceManager.GetString("Label_TRIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSS.
        /// </summary>
        public static string Label_TSS {
            get {
                return ResourceManager.GetString("Label_TSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Runner.
        /// </summary>
        public static string PowerRunner {
            get {
                return ResourceManager.GetString("PowerRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation version limited to creating power track for first {0} minutes of activity.  Upgrade to remove this message and create power track for full activity.  Activation can be done from the settings page.
        ///www.mechgt.com.
        /// </summary>
        public static string Text_EvalMessage {
            get {
                return ResourceManager.GetString("Text_EvalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power track created for {0} by {1} plugin v{2}.
        /// </summary>
        public static string Text_NotesMessage {
            get {
                return ResourceManager.GetString("Text_NotesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power track already contains data.  Overwrite?.
        /// </summary>
        public static string Text_OverwritePowerTrack {
            get {
                return ResourceManager.GetString("Text_OverwritePowerTrack", resourceCulture);
            }
        }
    }
}
